name: 'demo_project'
version: '1.0.0'
config-version: 2

profile: 'demo_project'


####################################
# Where will dbt look for my files?
#
####################################
model-paths: ["models"]
# python models now allowed         see https://docs.getdbt.com/docs/build/python-models
#
# doc blocks                        defined in a .md file (anywhere) using
#                                     {% docs __name__ %} ... {% enddocs %}
#                                   injected into documentation using
#                                     {{ doc("__name__") }}
#
# docs overview                     can be overwritten using
#                                     {% docs __overview__ %} ... {% enddocs %}
analysis-paths: ["analyses"]        # compiled to SQL for use elsehwere (not materialized)
test-paths: ["tests"]               
# 1. Data tests (post-run)          see https://docs.getdbt.com/docs/build/data-tests
# 2. Unit tests (pre-run)           see https://docs.getdbt.com/docs/build/unit-tests
seed-paths: ["seeds"]               # should be < 1 MB
macro-paths: ["macros"]             # custom SQL functions
snapshot-paths: ["snapshots"]       # used for SCDs when source does not track history


##################################################################
# What are all these files in the test/ directory?
#
# see https://docs.getdbt.com/reference/artifacts/other-artifacts
##################################################################


################################################
# Which directories are removed by `dbt clean`?
#
################################################
clean-targets:
  - "target"
  - "dbt_packages"
  

######################################################
# Configuring models
#
# see https://docs.getdbt.com/docs/configuring-models
######################################################
models:
  demo_project:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: table
